name: Test Python

on:
  push:
    branches:
      - main
  pull_request:
    types:
      - opened
      - synchronize


jobs:
  test:
    name: Run Pytest
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Download dataset
        run: make download-bash

      - name: Run mlflow
        run: make run_mlflow

      - name: Run Pytest
        run: |
          pytest
